name: posting_daily_challenges

on:
  schedule:
    - cron: '25 3 * * *'
  workflow_dispatch:

jobs:
  posting_the_daily_challenge_of_today:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: pip install -r requirements.txt --no-cache-dir

    - name: Run Python Script
      env:  ${{ secrets }} # this is absurd but works
      #env:
      #    WEBHOOK: ${{ secrets.WEBHOOK_PRODUCTION }}
      #    LABEL: ${{ secrets.LABEL }}
      #    TABLE202412: ${{ secrets.TABLE202412 }}
      #    TABLE202501: ${{ secrets.TABLE202501 }}
      #    TABLE202502: ${{ secrets.TABLE202502 }}
      run: python main.py
